name: C++ CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  all-in-one:
    name: Build, Analyze, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make cppcheck clang clang-tidy valgrind

      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --std=c++17 src include

      - name: Configure and Build Project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          make

      - name: Run Clang-Tidy
        run: |
          find src/ include/ -name "*.cpp" -o -name "*.hpp" | xargs clang-tidy -p build/ -- -std=c++17

      - name: Run Valgrind
        run: |
          cd build
          valgrind ./CircularBufferApp

      - name: Run Google Tests
        run: |
          cd build
          ctest --output-on-failure
