name: C++ CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cpp-workflow:
    name: C++ CI/CD Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make cppcheck clang clang-tidy valgrind

      # Step 1: Run Cppcheck
      - name: Run Cppcheck on src and include
        run: cppcheck --enable=all --inconclusive --std=c++17 src include

      # Step 2: Build the Project and Generate compile_commands.json
      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          make

      # Step 3: Run Clang-Tidy
      - name: Run Clang-Tidy
        run: |
          FILES=$(find src/ include/ -type f \( -name "*.cpp" -o -name "*.hpp" \))
          if [ -n "$FILES" ]; then
            echo "$FILES" | xargs clang-tidy -p build/ -- -std=c++17
          else
            echo "No source files found to run clang-tidy on."
          fi

      # Step 4: Run Valgrind on Executable
      - name: Run Valgrind
        run: |
          cd build
          if [ -f ./CircularBufferApp ]; then
            valgrind ./CircularBufferApp
          else
            echo "Executable not found: CircularBufferApp"
            exit 1
          fi

      # Step 5: Run Google Tests
      - name: Run Google Tests
        run: |
          cd build
          ctest --output-on-failure
