name: C++ CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cpp-workflow:
    name: C++ CI/CD Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make cppcheck clang clang-tidy valgrind

      # Step 1: Run Cppcheck
      - name: Run Cppcheck on src and include
        run: cppcheck --enable=all --inconclusive --std=c++17 src include

      # Step 2: Build the Project and Generate compile_commands.json
      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          make

      # Step 3: Run Google Tests
      - name: Run Google Tests
        run: |
          cd build
          ctest --output-on-failure
