name: C++ CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run Cppcheck
  cppcheck:
    name: Static Analysis with Cppcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run Cppcheck on src and include
        run: cppcheck --enable=all --inconclusive --std=c++17 src include

  # Job 2: Run Clang-Tidy
  clang-tidy:
    name: Static Analysis with Clang-Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Clang and Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang clang-tidy

      - name: Generate compile_commands.json
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

      - name: Run Clang-Tidy on src and include
        run: clang-tidy src/**/*.cpp include/**/*.hpp -p build/ -- -std=c++17

  # Job 3: Run Valgrind
  valgrind:
    name: Memory Analysis with Valgrind
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Build the Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Valgrind on Executable
        run: |
          cd build
          valgrind ./CircularBufferApp
